version: '3.8'

name: Football-project
services:
  api:
    container_name: api
    build: .
    command: npm run server
    image: node:16-alpine
    ports:
      - 3000:3000
    volumes:
      - .:/app

  postgres_db:
    container_name: football_db
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

    ports:
      - 3001:5432